### ISSUE TITLE
What is the main modifications of py-R-FCN-multiGPU compared to its precedent?

### ISSUE THREAD

**Issue by crazylyf** [bharatsingh430/py-R-FCN-multiGPU#3]
Hi @bharatsingh430 I have a self-maintained version of py-faster-rcnn, and now I want to add multiGPU support. Would you like kindly point out the main modifications so as to support multiGPU? Thank you!

**Comment by bharatsingh430** [comment]
You can look into the train_multi_gpu.py file in the fast_rcnn folder for the multi gpu part. I use the latest caffe branch which includes NCCL and then replace the batch norm layer in it with the one in py-r-fcn. ResNet would otherwise take 70-80% more memory if you use batch norm in the main repo. Other missing layers are also added, like ohem etc. So that each network on a different gpu operates on different set of images, random seed is set based on the GPU_ID in roi_data_layer/layer.py.

**Comment by crazylyf** [comment]
@bharatsingh430  Very nice of you, thank you!

**Comment by zimenglan-sysu-512** [comment]
@bharatsingh430 how do you modify the python code/layers to support the multi-gpu training and testing?
