### ISSUE TITLE
Any pascal voc results?

### ISSUE THREAD

**Issue by zengarden** [bharatsingh430/py-R-FCN-multiGPU#5]
hi,

I've run this code on pascal voc. train on voc"07+12" trainval and test on 07test.
Finally get 78.3mAP(averaged three experiments), but it seems a little bit lower than results provided by py-r-fcn. 

single gpu, iter_size 2: 78.3 (vs 79.4)
two gpu,  iter_size 1:  78.3 

bests
jemmy

**Comment by bharatsingh430** [comment]
If you check the R-FCN branch (the matlab one) it says that random seed can affect results by 1%. If you change the random seed from 3 to something else, you may get a better result. This is because when I use multi gpu, the batch sequence is not exactly same as py-r-fcn. This means that the pair of images in the n(th) batch are not the same in the two versions. I will change the code to ensure the same ordering with 2 GPUs and iter_size = 1 (although it's not a bug as such).

**Comment by 1292765944** [comment]
@bharatsingh430 Do you mean the RNG_SEED variable in config.py, it's initialised to 3 by default. However, in your code, the image list are independently randomized using gpu_id in layer.py .

**Comment by bharatsingh430** [comment]
Yes

**Comment by 1292765944** [comment]
@bharatsingh430 But I do not understand how the RNG_SEED influences the final results? Could you explain it more concretely?

**Comment by bharatsingh430** [comment]
since pascal is a small dataset, the training sequence can affect the accuracy to some extent because SGD is used
