### ISSUE TITLE
Error appears when running demo_rfcn.py

### ISSUE THREAD

**Issue by fighting-liu** [bharatsingh430/py-R-FCN-multiGPU#6]
Hello, is there anything wrong with your provided rfcn model?
When i run 'demo_rfcn.py', following message appears
![image](https://cloud.githubusercontent.com/assets/10908786/24287126/432d0b32-10b3-11e7-9f42-7d1d8dda4e79.png)

and when i run 'demo.py' for faster rcnn demo, everything runs fine.

**Comment by zhanghaoinf** [comment]
I got the same problem.

**Comment by bharatsingh430** [comment]
are you using the coco branch?

**Comment by zhanghaoinf** [comment]
I used the master branch, and caffe was built successfully. ( CUDA 8.0 with cuDNN ver5.1)

**Comment by bharatsingh430** [comment]
please read the readme

**Comment by zhanghaoinf** [comment]
Thank you, the multi-gpus model is training now.

**Comment by liu09114** [comment]
I have the same problem? Did you solve this problem, what's the method?
@zhanghaoinf @bharatsingh430

**Comment by zhanghaoinf** [comment]
Hi, @liu09114 , I checked before when I used the detection model published by msra (models store in onedrive), the problem will occur. If you initialize and train your own model with resnet-101 (classification model pre-trained on ImageNet-1000), the problem will disappear.  By the way, you need the coco branch to train your own model.

I think the sentence "If you want to use/train this model, please use the coco branch of this repository. " in the readme is important. :)

**Comment by zhanghaoinf** [comment]
@liu09114, I guess there might be a slightly difference (maybe names, args ... ) in the detection layers between original py-rfcn and py-rfcn-multi-gpu version, which causes the failure of loading models trained with py-rfcn which I am not sure.

**Comment by shohan6** [comment]
I have clone the coco branch by the following command
`git clone --recursive https://github.com/bharatsingh430/py-R-FCN-multiGPU/ --branch coco --single-branch
`
But `demo_rfcn.py` still not working. How to solve this issues @zhanghaoinf

**Comment by xmubingo** [comment]
I got this error too. so, what is the difference between py-rfcn and py-rfcn-multi-gpu version?

**Comment by zhanghaoinf** [comment]
@xmubingo Hi, it has been half a year since I last use py-rfcn-mulit-gpu. I try to answer this as much as I can. After cloning this repo, switch to coco branch ("git branch -a" to list all branches, "git checkout -b experimental XXX", use "git branch" to view the change). Try coco model provided in this repo <https://drive.google.com/file/d/0B6T5quL13CdHMGtMUWFFSXd2Ym8> instead of models downloaded from MSRA one drive.

**Comment by foralliance** [comment]
@xmubingo 
@shohan6 
Note 2 differences:
1. The name of the model is different. In the code, name is `resnet101_rfcn_final`,actual is `coco_rfcn.caffemodel`

2. Different paths, the code default is 
`cfg.models_dir = '/home/XXX/py-R-FCN-multiGPU-coco-branch/models/pascal_voc'`
The actual is:
`cfg.models_dir = '/home/XXX/py-R-FCN-multiGPU-coco-branch/models/coco'`
Because this is the coco data set training model
